/*
Deployment script for Veridata_Prod

This code was generated by a tool.
Changes to this file may cause incorrect behavior and will be lost if
the code is regenerated.
*/

GO
SET ANSI_NULLS, ANSI_PADDING, ANSI_WARNINGS, ARITHABORT, CONCAT_NULL_YIELDS_NULL, QUOTED_IDENTIFIER ON;

SET NUMERIC_ROUNDABORT OFF;


--GO
--:setvar DatabaseName "Veridata_Prod"
--:setvar DefaultFilePrefix "Veridata_Prod"
--:setvar DefaultDataPath "C:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS\MSSQL\DATA\"
--:setvar DefaultLogPath "C:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS\MSSQL\DATA\"

--GO
--:on error exit
--GO
--/*
--Detect SQLCMD mode and disable script execution if SQLCMD mode is not supported.
--To re-enable the script after enabling SQLCMD mode, execute the following:
--SET NOEXEC OFF; 
--*/
--:setvar __IsSqlCmdEnabled "True"
--GO
--IF N'$(__IsSqlCmdEnabled)' NOT LIKE N'True'
--    BEGIN
--        PRINT N'SQLCMD mode must be enabled to successfully execute this script.';
--        SET NOEXEC ON;
--    END


--GO
USE [Veridata_Prod];


GO
PRINT N'Starting rebuilding table [admin].[generalSetup]...';


GO
BEGIN TRANSACTION;

SET TRANSACTION ISOLATION LEVEL SERIALIZABLE;

SET XACT_ABORT ON;

CREATE TABLE [admin].[tmp_ms_xx_generalSetup] (
    [id]                INT      IDENTITY (1, 1) NOT NULL,
    [critical_no_days]  INT      NULL,
    [grace_period_days] INT      NULL,
    [active_status]     BIT      NULL,
    [created_by]        INT      NULL,
    [created_on]        DATETIME NULL,
    [updated_by]        INT      NULL,
    [updated_on]        DATETIME NULL,
    CONSTRAINT [tmp_ms_xx_constraint_PK_generalSetup1] PRIMARY KEY CLUSTERED ([id] ASC)
);

IF EXISTS (SELECT TOP 1 1 
           FROM   [admin].[generalSetup])
    BEGIN
        SET IDENTITY_INSERT [admin].[tmp_ms_xx_generalSetup] ON;
        INSERT INTO [admin].[tmp_ms_xx_generalSetup] ([id], [critical_no_days], [active_status], [created_by], [created_on], [updated_by], [updated_on])
        SELECT   [id],
                 [critical_no_days],
                 [active_status],
                 [created_by],
                 [created_on],
                 [updated_by],
                 [updated_on]
        FROM     [admin].[generalSetup]
        ORDER BY [id] ASC;
        SET IDENTITY_INSERT [admin].[tmp_ms_xx_generalSetup] OFF;
    END

DROP TABLE [admin].[generalSetup];

EXECUTE sp_rename N'[admin].[tmp_ms_xx_generalSetup]', N'generalSetup';

EXECUTE sp_rename N'[admin].[tmp_ms_xx_constraint_PK_generalSetup1]', N'PK_generalSetup', N'OBJECT';

COMMIT TRANSACTION;

SET TRANSACTION ISOLATION LEVEL READ COMMITTED;


GO
PRINT N'Starting rebuilding table [config].[api_couter_log]...';


GO
BEGIN TRANSACTION;

SET TRANSACTION ISOLATION LEVEL SERIALIZABLE;

SET XACT_ABORT ON;

CREATE TABLE [config].[tmp_ms_xx_api_couter_log] (
    [id]         BIGINT         IDENTITY (1, 1) NOT NULL,
    [api_name]   NVARCHAR (100) NOT NULL,
    [api_url]    NVARCHAR (50)  NOT NULL,
    [api_type]   NVARCHAR (50)  NULL,
    [api_status] INT            NULL,
    [payload]    TEXT           NULL,
    [created_on] DATETIME       NULL,
    [created_by] BIGINT         NOT NULL,
    CONSTRAINT [tmp_ms_xx_constraint_PK_api_couter_log1] PRIMARY KEY CLUSTERED ([id] ASC)
);

IF EXISTS (SELECT TOP 1 1 
           FROM   [config].[api_couter_log])
    BEGIN
        SET IDENTITY_INSERT [config].[tmp_ms_xx_api_couter_log] ON;
        INSERT INTO [config].[tmp_ms_xx_api_couter_log] ([id], [api_name], [api_url], [created_on], [created_by])
        SELECT   [id],
                 [api_name],
                 [api_url],
                 [created_on],
                 [created_by]
        FROM     [config].[api_couter_log]
        ORDER BY [id] ASC;
        SET IDENTITY_INSERT [config].[tmp_ms_xx_api_couter_log] OFF;
    END

DROP TABLE [config].[api_couter_log];

EXECUTE sp_rename N'[config].[tmp_ms_xx_api_couter_log]', N'api_couter_log';

EXECUTE sp_rename N'[config].[tmp_ms_xx_constraint_PK_api_couter_log1]', N'PK_api_couter_log', N'OBJECT';

COMMIT TRANSACTION;

SET TRANSACTION ISOLATION LEVEL READ COMMITTED;


GO
PRINT N'Creating Table [config].[appointee_update_log]...';


GO
CREATE TABLE [config].[appointee_update_log] (
    [id]           BIGINT         IDENTITY (1, 1) NOT NULL,
    [appointee_id] BIGINT         NULL,
    [candidate_id] NVARCHAR (20)  NULL,
    [update_type]  NVARCHAR (50)  NOT NULL,
    [update_value] NVARCHAR (100) NULL,
    [created_on]   DATETIME       NULL,
    [created_by]   BIGINT         NOT NULL,
    CONSTRAINT [PK_appointee_update_log] PRIMARY KEY CLUSTERED ([id] ASC)
);


GO
PRINT N'Creating Table [dbo].[raw_file_history_data]...';


GO
CREATE TABLE [dbo].[raw_file_history_data] (
    [rawfile_id]             BIGINT          IDENTITY (1, 1) NOT NULL,
    [file_id]                BIGINT          NOT NULL,
    [company_id]             INT             NOT NULL,
    [candidate_id]           NVARCHAR (100)  NULL,
    [appointee_name]         NVARCHAR (100)  NULL,
    [appointee_email]        NVARCHAR (50)   NULL,
    [mobile_no]              NVARCHAR (20)   NULL,
    [is_pf_verification_req] BIT             NULL,
    [joining_date]           DATETIME        NULL,
    [offer_date]             NVARCHAR (50)   NULL,
    [epf_wages]              NUMERIC (18, 2) NULL,
    [recruitment_hr]         NVARCHAR (50)   NULL,
    [people_manager]         NVARCHAR (50)   NULL,
    [active_status]          BIT             NULL,
    [created_by]             INT             NULL,
    [created_on]             DATETIME        NULL,
    [updated_by]             INT             NULL,
    [updated_on]             DATETIME        NULL,
    [company_id1]            INT             NULL,
    [file_id1]               BIGINT          NULL,
    [company_name]           NVARCHAR (50)   NULL,
    [level1_email]           NVARCHAR (50)   NULL,
    [level2_email]           NVARCHAR (50)   NULL,
    [level3_email]           NVARCHAR (50)   NULL,
    CONSTRAINT [PK_raw_file_history_data] PRIMARY KEY CLUSTERED ([rawfile_id] ASC)
);


GO
PRINT N'Creating Foreign Key [dbo].[FK_raw_file_history_data_company_company_id1]...';


GO
ALTER TABLE [dbo].[raw_file_history_data] WITH NOCHECK
    ADD CONSTRAINT [FK_raw_file_history_data_company_company_id1] FOREIGN KEY ([company_id1]) REFERENCES [admin].[company] ([company_id]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_raw_file_history_data_uploaded_xls_file_file_id1]...';


GO
ALTER TABLE [dbo].[raw_file_history_data] WITH NOCHECK
    ADD CONSTRAINT [FK_raw_file_history_data_uploaded_xls_file_file_id1] FOREIGN KEY ([file_id1]) REFERENCES [dbo].[uploaded_xls_file] ([file_id]);


GO
PRINT N'Checking existing data against newly created constraints';


GO
USE [Veridata_Prod];


GO
ALTER TABLE [dbo].[raw_file_history_data] WITH CHECK CHECK CONSTRAINT [FK_raw_file_history_data_company_company_id1];

ALTER TABLE [dbo].[raw_file_history_data] WITH CHECK CHECK CONSTRAINT [FK_raw_file_history_data_uploaded_xls_file_file_id1];


GO
PRINT N'Update complete.';


GO
