/*
Deployment script for veridataDev

This code was generated by a tool.
Changes to this file may cause incorrect behavior and will be lost if
the code is regenerated.
*/

GO
SET ANSI_NULLS, ANSI_PADDING, ANSI_WARNINGS, ARITHABORT, CONCAT_NULL_YIELDS_NULL, QUOTED_IDENTIFIER ON;

SET NUMERIC_ROUNDABORT OFF;


GO
:setvar DatabaseName "veridataDev"
:setvar DefaultFilePrefix "veridataDev"
:setvar DefaultDataPath "C:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS\MSSQL\DATA\"
:setvar DefaultLogPath "C:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS\MSSQL\DATA\"

GO
:on error exit
GO
/*
Detect SQLCMD mode and disable script execution if SQLCMD mode is not supported.
To re-enable the script after enabling SQLCMD mode, execute the following:
SET NOEXEC OFF; 
*/
:setvar __IsSqlCmdEnabled "True"
GO
IF N'$(__IsSqlCmdEnabled)' NOT LIKE N'True'
    BEGIN
        PRINT N'SQLCMD mode must be enabled to successfully execute this script.';
        SET NOEXEC ON;
    END


GO
USE [$(DatabaseName)];


GO
PRINT N'Dropping Index [admin].[escalation_setup].[IX_escalation_setup_level_id1]...';


GO
DROP INDEX [IX_escalation_setup_level_id1]
    ON [admin].[escalation_setup];


GO
PRINT N'Dropping Index [admin].[escaltionlevel_email_mapping].[IX_escaltionlevel_email_mapping_level_id1]...';


GO
DROP INDEX [IX_escaltionlevel_email_mapping_level_id1]
    ON [admin].[escaltionlevel_email_mapping];


GO
PRINT N'Dropping Index [admin].[menu_role_mapping].[IX_menu_role_mapping_menu_id1]...';


GO
DROP INDEX [IX_menu_role_mapping_menu_id1]
    ON [admin].[menu_role_mapping];


GO
PRINT N'Dropping Index [admin].[menu_role_mapping].[IX_menu_role_mapping_role_id1]...';


GO
DROP INDEX [IX_menu_role_mapping_role_id1]
    ON [admin].[menu_role_mapping];


GO
PRINT N'Dropping Index [admin].[role_user_mapping].[IX_role_user_mapping_role_id1]...';


GO
DROP INDEX [IX_role_user_mapping_role_id1]
    ON [admin].[role_user_mapping];


GO
PRINT N'Dropping Index [admin].[role_user_mapping].[IX_role_user_mapping_user_id1]...';


GO
DROP INDEX [IX_role_user_mapping_user_id1]
    ON [admin].[role_user_mapping];


GO
PRINT N'Dropping Index [admin].[user_authentication].[IX_user_authentication_user_id1]...';


GO
DROP INDEX [IX_user_authentication_user_id1]
    ON [admin].[user_authentication];


GO
PRINT N'Dropping Index [admin].[user_authentication_hist].[IX_user_authentication_hist_user_id1]...';


GO
DROP INDEX [IX_user_authentication_hist_user_id1]
    ON [admin].[user_authentication_hist];


GO
PRINT N'Dropping Index [admin].[user_master].[IX_user_master_role_id1]...';


GO
DROP INDEX [IX_user_master_role_id1]
    ON [admin].[user_master];


GO
PRINT N'Dropping Index [dbo].[appointee_details].[IX_appointee_details_appointee_id1]...';


GO
DROP INDEX [IX_appointee_details_appointee_id1]
    ON [dbo].[appointee_details];


GO
PRINT N'Dropping Index [dbo].[appointee_details].[IX_appointee_details_company_id1]...';


GO
DROP INDEX [IX_appointee_details_company_id1]
    ON [dbo].[appointee_details];


GO
PRINT N'Dropping Index [dbo].[appointee_reason_details].[IX_appointee_reason_details_appointee_id1]...';


GO
DROP INDEX [IX_appointee_reason_details_appointee_id1]
    ON [dbo].[appointee_reason_details];


GO
PRINT N'Dropping Index [dbo].[processed_file_data].[IX_processed_file_data_appointee_id1]...';


GO
DROP INDEX [IX_processed_file_data_appointee_id1]
    ON [dbo].[processed_file_data];


GO
PRINT N'Dropping Index [dbo].[processed_file_data].[IX_processed_file_data_file_id]...';


GO
DROP INDEX [IX_processed_file_data_file_id]
    ON [dbo].[processed_file_data];


GO
PRINT N'Dropping Index [dbo].[raw_file_data].[IX_raw_file_data_company_id1]...';


GO
DROP INDEX [IX_raw_file_data_company_id1]
    ON [dbo].[raw_file_data];


GO
PRINT N'Dropping Index [dbo].[raw_file_data].[IX_raw_file_data_file_id1]...';


GO
DROP INDEX [IX_raw_file_data_file_id1]
    ON [dbo].[raw_file_data];


GO
PRINT N'Dropping Index [dbo].[rejected_file_data].[IX_rejected_file_data_appointee_id1]...';


GO
DROP INDEX [IX_rejected_file_data_appointee_id1]
    ON [dbo].[rejected_file_data];


GO
PRINT N'Dropping Index [dbo].[under_process_file_data].[IX_under_process_file_data_company_id1]...';


GO
DROP INDEX [IX_under_process_file_data_company_id1]
    ON [dbo].[under_process_file_data];


GO
PRINT N'Dropping Index [dbo].[under_process_file_data].[IX_under_process_file_data_file_id1]...';


GO
DROP INDEX [IX_under_process_file_data_file_id1]
    ON [dbo].[under_process_file_data];


GO
PRINT N'Dropping Index [dbo].[unprocessed_file_data].[IX_unprocessed_file_data_company_id1]...';


GO
DROP INDEX [IX_unprocessed_file_data_company_id1]
    ON [dbo].[unprocessed_file_data];


GO
PRINT N'Dropping Index [dbo].[unprocessed_file_data].[IX_unprocessed_file_data_file_id1]...';


GO
DROP INDEX [IX_unprocessed_file_data_file_id1]
    ON [dbo].[unprocessed_file_data];


GO
PRINT N'Dropping Index [dbo].[upload_details].[IX_upload_details_appointee_id1]...';


GO
DROP INDEX [IX_upload_details_appointee_id1]
    ON [dbo].[upload_details];


GO
PRINT N'Dropping Index [dbo].[upload_details].[IX_upload_details_company_id]...';


GO
DROP INDEX [IX_upload_details_company_id]
    ON [dbo].[upload_details];


GO
PRINT N'Dropping Index [dbo].[upload_details].[IX_upload_details_upload_type_id1]...';


GO
DROP INDEX [IX_upload_details_upload_type_id1]
    ON [dbo].[upload_details];


GO
PRINT N'Dropping Default Constraint [master].[DF_reason_master_created_on]...';


GO
ALTER TABLE [master].[reason_master] DROP CONSTRAINT [DF_reason_master_created_on];


GO
PRINT N'Dropping Foreign Key [admin].[FK_escalation_setup_escalationlevel_master_level_id1]...';


GO
ALTER TABLE [admin].[escalation_setup] DROP CONSTRAINT [FK_escalation_setup_escalationlevel_master_level_id1];


GO
PRINT N'Dropping Foreign Key [admin].[FK_user_authentication_user_master_user_id1]...';


GO
ALTER TABLE [admin].[user_authentication] DROP CONSTRAINT [FK_user_authentication_user_master_user_id1];


GO
PRINT N'Dropping Foreign Key [admin].[FK_user_authentication_hist_user_master_user_id1]...';


GO
ALTER TABLE [admin].[user_authentication_hist] DROP CONSTRAINT [FK_user_authentication_hist_user_master_user_id1];


GO
PRINT N'Starting rebuilding table [admin].[escalation_case_master]...';


GO
BEGIN TRANSACTION;

SET TRANSACTION ISOLATION LEVEL SERIALIZABLE;

SET XACT_ABORT ON;

CREATE TABLE [admin].[tmp_ms_xx_escalation_case_master] (
    [case_id]       INT            IDENTITY (1, 1) NOT NULL,
    [setup_code]    NVARCHAR (10)  NULL,
    [setup_desc]    NVARCHAR (100) NULL,
    [setup_alias]   NVARCHAR (10)  NULL,
    [active_status] BIT            NULL,
    [created_by]    INT            NULL,
    [created_on]    DATETIME       NULL,
    [updated_by]    INT            NULL,
    [updated_on]    DATETIME       NULL,
    CONSTRAINT [tmp_ms_xx_constraint_PK_escalation_case_master1] PRIMARY KEY CLUSTERED ([case_id] ASC)
);

IF EXISTS (SELECT TOP 1 1 
           FROM   [admin].[escalation_case_master])
    BEGIN
        SET IDENTITY_INSERT [admin].[tmp_ms_xx_escalation_case_master] ON;
        INSERT INTO [admin].[tmp_ms_xx_escalation_case_master] ([case_id], [setup_code], [setup_desc], [active_status], [created_by], [created_on], [updated_by], [updated_on])
        SELECT   [case_id],
                 [setup_code],
                 [setup_desc],
                 [active_status],
                 [created_by],
                 [created_on],
                 [updated_by],
                 [updated_on]
        FROM     [admin].[escalation_case_master]
        ORDER BY [case_id] ASC;
        SET IDENTITY_INSERT [admin].[tmp_ms_xx_escalation_case_master] OFF;
    END

DROP TABLE [admin].[escalation_case_master];

EXECUTE sp_rename N'[admin].[tmp_ms_xx_escalation_case_master]', N'escalation_case_master';

EXECUTE sp_rename N'[admin].[tmp_ms_xx_constraint_PK_escalation_case_master1]', N'PK_escalation_case_master', N'OBJECT';

COMMIT TRANSACTION;

SET TRANSACTION ISOLATION LEVEL READ COMMITTED;


GO
PRINT N'Starting rebuilding table [admin].[escalation_setup]...';


GO
BEGIN TRANSACTION;

SET TRANSACTION ISOLATION LEVEL SERIALIZABLE;

SET XACT_ABORT ON;

CREATE TABLE [admin].[tmp_ms_xx_escalation_setup] (
    [setup_id]      INT           IDENTITY (1, 1) NOT NULL,
    [level_id]      INT           NOT NULL,
    [case_id]       INT           NOT NULL,
    [setup_option]  BIT           NULL,
    [email_id]      NVARCHAR (50) NULL,
    [active_status] BIT           NULL,
    [created_by]    INT           NULL,
    [created_on]    DATETIME      NULL,
    [updated_by]    INT           NULL,
    [updated_on]    DATETIME      NULL,
    [level_id1]     INT           NULL,
    CONSTRAINT [tmp_ms_xx_constraint_PK_escalation_setup1] PRIMARY KEY CLUSTERED ([setup_id] ASC)
);

IF EXISTS (SELECT TOP 1 1 
           FROM   [admin].[escalation_setup])
    BEGIN
        SET IDENTITY_INSERT [admin].[tmp_ms_xx_escalation_setup] ON;
        INSERT INTO [admin].[tmp_ms_xx_escalation_setup] ([setup_id], [level_id], [case_id], [setup_option], [active_status], [created_by], [created_on], [updated_by], [updated_on], [level_id1])
        SELECT   [setup_id],
                 [level_id],
                 [case_id],
                 [setup_option],
                 [active_status],
                 [created_by],
                 [created_on],
                 [updated_by],
                 [updated_on],
                 [level_id1]
        FROM     [admin].[escalation_setup]
        ORDER BY [setup_id] ASC;
        SET IDENTITY_INSERT [admin].[tmp_ms_xx_escalation_setup] OFF;
    END

DROP TABLE [admin].[escalation_setup];

EXECUTE sp_rename N'[admin].[tmp_ms_xx_escalation_setup]', N'escalation_setup';

EXECUTE sp_rename N'[admin].[tmp_ms_xx_constraint_PK_escalation_setup1]', N'PK_escalation_setup', N'OBJECT';

COMMIT TRANSACTION;

SET TRANSACTION ISOLATION LEVEL READ COMMITTED;


GO
PRINT N'Altering Table [admin].[escalationlevel_master]...';


GO
ALTER TABLE [admin].[escalationlevel_master]
    ADD [setup_alias] NVARCHAR (10) NULL;


GO
PRINT N'Starting rebuilding table [admin].[generalSetup]...';


GO
BEGIN TRANSACTION;

SET TRANSACTION ISOLATION LEVEL SERIALIZABLE;

SET XACT_ABORT ON;

CREATE TABLE [admin].[tmp_ms_xx_generalSetup] (
    [id]                INT      IDENTITY (1, 1) NOT NULL,
    [critical_no_days]  INT      NULL,
    [grace_period_days] INT      NULL,
    [active_status]     BIT      NULL,
    [created_by]        INT      NULL,
    [created_on]        DATETIME NULL,
    [updated_by]        INT      NULL,
    [updated_on]        DATETIME NULL,
    CONSTRAINT [tmp_ms_xx_constraint_PK_generalSetup1] PRIMARY KEY CLUSTERED ([id] ASC)
);

IF EXISTS (SELECT TOP 1 1 
           FROM   [admin].[generalSetup])
    BEGIN
        SET IDENTITY_INSERT [admin].[tmp_ms_xx_generalSetup] ON;
        INSERT INTO [admin].[tmp_ms_xx_generalSetup] ([id], [critical_no_days], [active_status], [created_by], [created_on], [updated_by], [updated_on])
        SELECT   [id],
                 [critical_no_days],
                 [active_status],
                 [created_by],
                 [created_on],
                 [updated_by],
                 [updated_on]
        FROM     [admin].[generalSetup]
        ORDER BY [id] ASC;
        SET IDENTITY_INSERT [admin].[tmp_ms_xx_generalSetup] OFF;
    END

DROP TABLE [admin].[generalSetup];

EXECUTE sp_rename N'[admin].[tmp_ms_xx_generalSetup]', N'generalSetup';

EXECUTE sp_rename N'[admin].[tmp_ms_xx_constraint_PK_generalSetup1]', N'PK_generalSetup', N'OBJECT';

COMMIT TRANSACTION;

SET TRANSACTION ISOLATION LEVEL READ COMMITTED;


GO
PRINT N'Starting rebuilding table [admin].[user_authentication]...';


GO
BEGIN TRANSACTION;

SET TRANSACTION ISOLATION LEVEL SERIALIZABLE;

SET XACT_ABORT ON;

CREATE TABLE [admin].[tmp_ms_xx_user_authentication] (
    [user_autho_id]    BIGINT         IDENTITY (1, 1) NOT NULL,
    [user_id]          BIGINT         NOT NULL,
    [user_pwd]         NVARCHAR (100) NULL,
    [user_pwd_txt]     NVARCHAR (10)  NULL,
    [user_profile_pwd] NVARCHAR (100) NULL,
    [is_default_pass]  CHAR (1)       NULL,
    [active_status]    BIT            NULL,
    [created_by]       INT            NULL,
    [created_on]       DATETIME       NULL,
    [updated_by]       INT            NULL,
    [updated_on]       DATETIME       NULL,
    [user_id1]         BIGINT         NULL,
    CONSTRAINT [tmp_ms_xx_constraint_PK_user_authentication1] PRIMARY KEY CLUSTERED ([user_autho_id] ASC)
);

IF EXISTS (SELECT TOP 1 1 
           FROM   [admin].[user_authentication])
    BEGIN
        SET IDENTITY_INSERT [admin].[tmp_ms_xx_user_authentication] ON;
        INSERT INTO [admin].[tmp_ms_xx_user_authentication] ([user_autho_id], [user_id], [user_pwd], [user_pwd_txt], [is_default_pass], [active_status], [created_by], [created_on], [updated_by], [updated_on], [user_id1])
        SELECT   [user_autho_id],
                 [user_id],
                 [user_pwd],
                 [user_pwd_txt],
                 [is_default_pass],
                 [active_status],
                 [created_by],
                 [created_on],
                 [updated_by],
                 [updated_on],
                 [user_id1]
        FROM     [admin].[user_authentication]
        ORDER BY [user_autho_id] ASC;
        SET IDENTITY_INSERT [admin].[tmp_ms_xx_user_authentication] OFF;
    END

DROP TABLE [admin].[user_authentication];

EXECUTE sp_rename N'[admin].[tmp_ms_xx_user_authentication]', N'user_authentication';

EXECUTE sp_rename N'[admin].[tmp_ms_xx_constraint_PK_user_authentication1]', N'PK_user_authentication', N'OBJECT';

COMMIT TRANSACTION;

SET TRANSACTION ISOLATION LEVEL READ COMMITTED;


GO
PRINT N'Starting rebuilding table [admin].[user_authentication_hist]...';


GO
BEGIN TRANSACTION;

SET TRANSACTION ISOLATION LEVEL SERIALIZABLE;

SET XACT_ABORT ON;

CREATE TABLE [admin].[tmp_ms_xx_user_authentication_hist] (
    [autho_hist_id] INT            IDENTITY (1, 1) NOT NULL,
    [user_id]       BIGINT         NOT NULL,
    [client_id]     NVARCHAR (100) NULL,
    [entry_time]    DATETIME       NULL,
    [exit_time]     DATETIME       NULL,
    [ip_address]    NVARCHAR (50)  NULL,
    [gip_address]   NVARCHAR (50)  NULL,
    [browser_name]  NVARCHAR (50)  NULL,
    [token_no]      NVARCHAR (50)  NULL,
    [otp_no]        NVARCHAR (10)  NULL,
    [exit_status]   NVARCHAR (10)  NULL,
    [active_status] BIT            NULL,
    [created_by]    INT            NULL,
    [created_on]    DATETIME       NULL,
    [updated_by]    INT            NULL,
    [updated_on]    DATETIME       NULL,
    [user_id1]      BIGINT         NULL,
    CONSTRAINT [tmp_ms_xx_constraint_PK_user_authentication_hist1] PRIMARY KEY CLUSTERED ([autho_hist_id] ASC)
);

IF EXISTS (SELECT TOP 1 1 
           FROM   [admin].[user_authentication_hist])
    BEGIN
        SET IDENTITY_INSERT [admin].[tmp_ms_xx_user_authentication_hist] ON;
        INSERT INTO [admin].[tmp_ms_xx_user_authentication_hist] ([autho_hist_id], [user_id], [entry_time], [exit_time], [ip_address], [gip_address], [browser_name], [token_no], [exit_status], [active_status], [created_by], [created_on], [updated_by], [updated_on], [user_id1])
        SELECT   [autho_hist_id],
                 [user_id],
                 [entry_time],
                 [exit_time],
                 [ip_address],
                 [gip_address],
                 [browser_name],
                 [token_no],
                 [exit_status],
                 [active_status],
                 [created_by],
                 [created_on],
                 [updated_by],
                 [updated_on],
                 [user_id1]
        FROM     [admin].[user_authentication_hist]
        ORDER BY [autho_hist_id] ASC;
        SET IDENTITY_INSERT [admin].[tmp_ms_xx_user_authentication_hist] OFF;
    END

DROP TABLE [admin].[user_authentication_hist];

EXECUTE sp_rename N'[admin].[tmp_ms_xx_user_authentication_hist]', N'user_authentication_hist';

EXECUTE sp_rename N'[admin].[tmp_ms_xx_constraint_PK_user_authentication_hist1]', N'PK_user_authentication_hist', N'OBJECT';

COMMIT TRANSACTION;

SET TRANSACTION ISOLATION LEVEL READ COMMITTED;


GO
PRINT N'Starting rebuilding table [config].[api_couter_log]...';


GO
BEGIN TRANSACTION;

SET TRANSACTION ISOLATION LEVEL SERIALIZABLE;

SET XACT_ABORT ON;

CREATE TABLE [config].[tmp_ms_xx_api_couter_log] (
    [id]         BIGINT         IDENTITY (1, 1) NOT NULL,
    [api_name]   NVARCHAR (100) NOT NULL,
    [api_url]    NVARCHAR (50)  NOT NULL,
    [api_type]   NVARCHAR (50)  NULL,
    [api_status] INT            NULL,
    [payload]    TEXT           NULL,
    [created_on] DATETIME       NULL,
    [created_by] BIGINT         NOT NULL,
    CONSTRAINT [tmp_ms_xx_constraint_PK_api_couter_log1] PRIMARY KEY CLUSTERED ([id] ASC)
);

IF EXISTS (SELECT TOP 1 1 
           FROM   [config].[api_couter_log])
    BEGIN
        SET IDENTITY_INSERT [config].[tmp_ms_xx_api_couter_log] ON;
        INSERT INTO [config].[tmp_ms_xx_api_couter_log] ([id], [api_name], [api_url], [created_on], [created_by])
        SELECT   [id],
                 [api_name],
                 [api_url],
                 [created_on],
                 [created_by]
        FROM     [config].[api_couter_log]
        ORDER BY [id] ASC;
        SET IDENTITY_INSERT [config].[tmp_ms_xx_api_couter_log] OFF;
    END

DROP TABLE [config].[api_couter_log];

EXECUTE sp_rename N'[config].[tmp_ms_xx_api_couter_log]', N'api_couter_log';

EXECUTE sp_rename N'[config].[tmp_ms_xx_constraint_PK_api_couter_log1]', N'PK_api_couter_log', N'OBJECT';

COMMIT TRANSACTION;

SET TRANSACTION ISOLATION LEVEL READ COMMITTED;


GO
PRINT N'Altering Table [dbo].[appointee_details]...';


GO
ALTER TABLE [dbo].[appointee_details] ALTER COLUMN [passport_no] NVARCHAR (200) NULL;

ALTER TABLE [dbo].[appointee_details] ALTER COLUMN [uan_number] NVARCHAR (100) NULL;


GO
ALTER TABLE [dbo].[appointee_details]
    ADD [level1_email] NVARCHAR (50) NULL,
        [level2_email] NVARCHAR (50) NULL,
        [level3_email] NVARCHAR (50) NULL;


GO
PRINT N'Altering Table [dbo].[raw_file_data]...';


GO
ALTER TABLE [dbo].[raw_file_data]
    ADD [level1_email] NVARCHAR (50) NULL,
        [level2_email] NVARCHAR (50) NULL,
        [level3_email] NVARCHAR (50) NULL;


GO
PRINT N'Altering Table [dbo].[under_process_file_data]...';


GO
ALTER TABLE [dbo].[under_process_file_data]
    ADD [level1_email] NVARCHAR (50) NULL,
        [level2_email] NVARCHAR (50) NULL,
        [level3_email] NVARCHAR (50) NULL;


GO
PRINT N'Altering Table [dbo].[unprocessed_file_data]...';


GO
ALTER TABLE [dbo].[unprocessed_file_data]
    ADD [level1_email] NVARCHAR (50) NULL,
        [level2_email] NVARCHAR (50) NULL,
        [level3_email] NVARCHAR (50) NULL;


GO
PRINT N'Starting rebuilding table [master].[reason_master]...';


GO
BEGIN TRANSACTION;

SET TRANSACTION ISOLATION LEVEL SERIALIZABLE;

SET XACT_ABORT ON;

CREATE TABLE [master].[tmp_ms_xx_reason_master] (
    [reason_id]       INT            IDENTITY (1, 1) NOT NULL,
    [reason_type]     NVARCHAR (10)  NULL,
    [reason_category] NVARCHAR (10)  NULL,
    [reason_code]     NVARCHAR (10)  NULL,
    [reason_info]     NVARCHAR (200) NULL,
    [reason_remedy]   NVARCHAR (MAX) NULL,
    [active_status]   BIT            NULL,
    [created_by]      INT            NULL,
    [created_on]      DATETIME       CONSTRAINT [DF_reason_master_created_on] DEFAULT (getdate()) NULL,
    [updated_by]      INT            NULL,
    [updated_on]      DATETIME       NULL,
    CONSTRAINT [tmp_ms_xx_constraint_PK_reason_master1] PRIMARY KEY CLUSTERED ([reason_id] ASC)
);

IF EXISTS (SELECT TOP 1 1 
           FROM   [master].[reason_master])
    BEGIN
        SET IDENTITY_INSERT [master].[tmp_ms_xx_reason_master] ON;
        INSERT INTO [master].[tmp_ms_xx_reason_master] ([reason_id], [reason_type], [reason_code], [reason_info], [reason_remedy], [active_status], [created_by], [created_on], [updated_by], [updated_on])
        SELECT   [reason_id],
                 [reason_type],
                 [reason_code],
                 [reason_info],
                 [reason_remedy],
                 [active_status],
                 [created_by],
                 [created_on],
                 [updated_by],
                 [updated_on]
        FROM     [master].[reason_master]
        ORDER BY [reason_id] ASC;
        SET IDENTITY_INSERT [master].[tmp_ms_xx_reason_master] OFF;
    END

DROP TABLE [master].[reason_master];

EXECUTE sp_rename N'[master].[tmp_ms_xx_reason_master]', N'reason_master';

EXECUTE sp_rename N'[master].[tmp_ms_xx_constraint_PK_reason_master1]', N'PK_reason_master', N'OBJECT';

COMMIT TRANSACTION;

SET TRANSACTION ISOLATION LEVEL READ COMMITTED;


GO
PRINT N'Creating Table [activity].[appointee_update_activity]...';


GO
CREATE TABLE [activity].[appointee_update_activity] (
    [activity_id]   INT            IDENTITY (1, 1) NOT NULL,
    [appointee_id]  INT            NOT NULL,
    [update_type]   NVARCHAR (50)  NULL,
    [update_value]  NVARCHAR (100) NULL,
    [active_status] BIT            NULL,
    [created_by]    INT            NULL,
    [created_on]    DATETIME       NULL,
    CONSTRAINT [PK_appointee_update_activity] PRIMARY KEY CLUSTERED ([activity_id] ASC)
);


GO
PRINT N'Creating Table [config].[appointee_update_log]...';


GO
CREATE TABLE [config].[appointee_update_log] (
    [id]           BIGINT         IDENTITY (1, 1) NOT NULL,
    [appointee_id] BIGINT         NULL,
    [candidate_id] NVARCHAR (20)  NULL,
    [update_type]  NVARCHAR (50)  NOT NULL,
    [update_value] NVARCHAR (100) NULL,
    [created_on]   DATETIME       NULL,
    [created_by]   BIGINT         NOT NULL,
    CONSTRAINT [PK_appointee_update_log] PRIMARY KEY CLUSTERED ([id] ASC)
);


GO
PRINT N'Creating Table [dbo].[raw_file_history_data]...';


GO
CREATE TABLE [dbo].[raw_file_history_data] (
    [rawfile_id]             BIGINT          IDENTITY (1, 1) NOT NULL,
    [file_id]                BIGINT          NOT NULL,
    [company_id]             INT             NOT NULL,
    [candidate_id]           NVARCHAR (100)  NULL,
    [appointee_name]         NVARCHAR (100)  NULL,
    [appointee_email]        NVARCHAR (50)   NULL,
    [mobile_no]              NVARCHAR (20)   NULL,
    [is_pf_verification_req] BIT             NULL,
    [joining_date]           DATETIME        NULL,
    [offer_date]             NVARCHAR (50)   NULL,
    [epf_wages]              NUMERIC (18, 2) NULL,
    [recruitment_hr]         NVARCHAR (50)   NULL,
    [people_manager]         NVARCHAR (50)   NULL,
    [active_status]          BIT             NULL,
    [created_by]             INT             NULL,
    [created_on]             DATETIME        NULL,
    [updated_by]             INT             NULL,
    [updated_on]             DATETIME        NULL,
    [company_id1]            INT             NULL,
    [file_id1]               BIGINT          NULL,
    [company_name]           NVARCHAR (50)   NULL,
    [level1_email]           NVARCHAR (50)   NULL,
    [level2_email]           NVARCHAR (50)   NULL,
    [level3_email]           NVARCHAR (50)   NULL,
    CONSTRAINT [PK_raw_file_history_data] PRIMARY KEY CLUSTERED ([rawfile_id] ASC)
);


GO
PRINT N'Creating Foreign Key [admin].[FK_escalation_setup_escalationlevel_master_level_id1]...';


GO
ALTER TABLE [admin].[escalation_setup] WITH NOCHECK
    ADD CONSTRAINT [FK_escalation_setup_escalationlevel_master_level_id1] FOREIGN KEY ([level_id1]) REFERENCES [admin].[escalationlevel_master] ([level_id]);


GO
PRINT N'Creating Foreign Key [admin].[FK_user_authentication_user_master_user_id1]...';


GO
ALTER TABLE [admin].[user_authentication] WITH NOCHECK
    ADD CONSTRAINT [FK_user_authentication_user_master_user_id1] FOREIGN KEY ([user_id1]) REFERENCES [admin].[user_master] ([user_id]);


GO
PRINT N'Creating Foreign Key [admin].[FK_user_authentication_hist_user_master_user_id1]...';


GO
ALTER TABLE [admin].[user_authentication_hist] WITH NOCHECK
    ADD CONSTRAINT [FK_user_authentication_hist_user_master_user_id1] FOREIGN KEY ([user_id1]) REFERENCES [admin].[user_master] ([user_id]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_raw_file_history_data_company_company_id1]...';


GO
ALTER TABLE [dbo].[raw_file_history_data] WITH NOCHECK
    ADD CONSTRAINT [FK_raw_file_history_data_company_company_id1] FOREIGN KEY ([company_id1]) REFERENCES [admin].[company] ([company_id]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_raw_file_history_data_uploaded_xls_file_file_id1]...';


GO
ALTER TABLE [dbo].[raw_file_history_data] WITH NOCHECK
    ADD CONSTRAINT [FK_raw_file_history_data_uploaded_xls_file_file_id1] FOREIGN KEY ([file_id1]) REFERENCES [dbo].[uploaded_xls_file] ([file_id]);


GO
PRINT N'Checking existing data against newly created constraints';


GO
USE [$(DatabaseName)];


GO
ALTER TABLE [admin].[escalation_setup] WITH CHECK CHECK CONSTRAINT [FK_escalation_setup_escalationlevel_master_level_id1];

ALTER TABLE [admin].[user_authentication] WITH CHECK CHECK CONSTRAINT [FK_user_authentication_user_master_user_id1];

ALTER TABLE [admin].[user_authentication_hist] WITH CHECK CHECK CONSTRAINT [FK_user_authentication_hist_user_master_user_id1];

ALTER TABLE [dbo].[raw_file_history_data] WITH CHECK CHECK CONSTRAINT [FK_raw_file_history_data_company_company_id1];

ALTER TABLE [dbo].[raw_file_history_data] WITH CHECK CHECK CONSTRAINT [FK_raw_file_history_data_uploaded_xls_file_file_id1];


GO
PRINT N'Update complete.';


GO
