CREATE TABLE [dbo].[appointee_details] (
    [appointee_details_id]   BIGINT          IDENTITY (1, 1) NOT NULL,
    [appointee_id]           BIGINT          NOT NULL,
    [company_id]             INT             NOT NULL,
    [candidate_id]           NVARCHAR (100)  NULL,
    [appointee_name]         NVARCHAR (100)  NULL,
    [appointee_email]        NVARCHAR (50)   NULL,
    [date_of_birth]          DATETIME        NULL,
    [gender]                 CHAR (1)        NULL,
    [mobile_no]              NVARCHAR (20)   NULL,
    [uan_number]             NVARCHAR (100)   NULL,
    [joining_date]           DATETIME        NULL,
    [member_name]            NVARCHAR (50)   NULL,
    [member_relation]        CHAR (1)        NULL,
    [nationality]            NVARCHAR (50)   NULL,
    [epf_wages]              NUMERIC (18, 2) NOT NULL,
    [qualification]          CHAR (1)        NULL,
    [maratialstatus]         CHAR (1)        NULL,
    [is_passportAvailable]   CHAR (1)        NULL,
    [is_internationalworker] CHAR (1)        NULL,
    [origincountry]          NVARCHAR (50)   NULL,
    [passport_no]            NVARCHAR (200)   NULL,
    [passport_validfrom]     DATETIME        NULL,
    [passport_validtill]     DATETIME        NULL,
    [passport_fileno]        NVARCHAR (50)   NULL,
    [is_handicap]            CHAR (1)        NULL,
    [handicape_type]         NVARCHAR (50)   NULL,
    [is_pf_verification_req] BIT             NULL,
    [aadhaar_name]           NVARCHAR (100)  NULL,
    [name_from_aadhaar]      NVARCHAR (100)  NULL,
    [dob_from_aadhaar]       NVARCHAR (20)   NULL,
    [gender_from_aadhaar]    NVARCHAR (10)   NULL,
    [aadhaar_number]         NVARCHAR (100)  NULL,
    [aadhaar_number_view]    NVARCHAR (50)   NULL,
    [pan_name]               NVARCHAR (100)  NULL,
    [pan_number]             NVARCHAR (50)   NULL,
    [is_processed]           BIT             NULL,
    [is_pensionapplicable]   BIT             NULL,
    [is_aadhaarvarified]     BIT             NULL,
    [is_passportvarified]    BIT             NULL,
    [is_uanvarified]         BIT             NULL,
    [is_fnamevarified]       BIT             NULL,
    [is_passbook_fetch]      BIT             NULL,
    [is_manual_passbook]     BIT             NULL,
    [save_step]              INT             NULL,
    [process_status]         INT             NULL,
    [active_status]          BIT             NULL,
    [is_save]                BIT             NULL,
    [is_submit]              BIT             NULL,
    [is_offline_kyc]         BIT             NULL,
    [created_by]             INT             NULL,
    [created_on]             DATETIME        NULL,
    [updated_by]             INT             NULL,
    [updated_on]             DATETIME        NULL,
    [appointee_id1]          BIGINT          NULL,
    [company_id1]            INT             NULL,
    [fathers_name_from_pan]  NVARCHAR (100)  NULL,
    [is_panvarified]         BIT             NULL,
    [company_name]           NVARCHAR (50)   NULL,
    [is_trustpassbook]       BIT             NULL,
  
    [level1_email]           NVARCHAR (50)   NULL,
    [level2_email]           NVARCHAR (50)   NULL,
    [level3_email]           NVARCHAR (50)   NULL,
    [is_uan_available] BIT NULL, 
    [is_pensiongap] BIT NULL, 
    [is_uan_aadhar_link] BIT NULL, 
    CONSTRAINT [PK_appointee_details] PRIMARY KEY CLUSTERED ([appointee_details_id] ASC),
    CONSTRAINT [FK_appointee_details_appointee_master_appointee_id1] FOREIGN KEY ([appointee_id1]) REFERENCES [dbo].[appointee_master] ([appointee_id]),
    CONSTRAINT [FK_appointee_details_company_company_id1] FOREIGN KEY ([company_id1]) REFERENCES [admin].[company] ([company_id])
);

