CREATE TABLE [dbo].[unprocessed_file_data] (
    [unprocessed_id]         BIGINT          IDENTITY (1, 1) NOT NULL,
    [file_id]                BIGINT          NOT NULL,
    [company_id]             INT             NOT NULL,
    [candidate_id]           NVARCHAR (100)  NULL,
    [appointee_name]         NVARCHAR (100)  NULL,
    [appointee_email]        NVARCHAR (50)   NULL,
    [mobile_no]              NVARCHAR (20)   NULL,
    [is_pf_verification_req] BIT             NULL,
    [joining_date]           DATETIME        NULL,
    [offer_date]             DATETIME        NULL,
    [epf_wages]              NUMERIC (18, 2) NULL,
    [recruitment_hr]         NVARCHAR (50)   NULL,
    [people_manager]         NVARCHAR (50)   NULL,
    [reason_to_unprocess]    NVARCHAR (MAX)  NULL,
    [active_status]          BIT             NULL,
    [created_by]             INT             NULL,
    [created_on]             DATETIME        NULL,
    [updated_by]             INT             NULL,
    [updated_on]             DATETIME        NULL,
    [company_id1]            INT             NULL,
    [file_id1]               BIGINT          NULL,
    [company_name]           NVARCHAR (50)   NULL,
    [level1_email]           NVARCHAR (50)   NULL,
    [level2_email]           NVARCHAR (50)   NULL,
    [level3_email]           NVARCHAR (50)   NULL,
    CONSTRAINT [PK_unprocessed_file_data] PRIMARY KEY CLUSTERED ([unprocessed_id] ASC),
    CONSTRAINT [FK_unprocessed_file_data_company_company_id1] FOREIGN KEY ([company_id1]) REFERENCES [admin].[company] ([company_id]),
    CONSTRAINT [FK_unprocessed_file_data_uploaded_xls_file_file_id1] FOREIGN KEY ([file_id1]) REFERENCES [dbo].[uploaded_xls_file] ([file_id])
);

